const STORAGE_KEY = "fruitin-decisions-v1";
const FALLBACK_FRUITS = [["maca-verde","Maçã verde","🍏"],["maca-vermelha","Maçã vermelha","🍎"],["pera","Pera","🍐"],["laranja","Laranja","🍊"],["tangerina","Tangerina","🍊"],["limao","Limão","🍋"],["limao-siciliano","Limão-siciliano","🍋"],["banana","Banana","🍌"],["melancia","Melancia","🍉"],["uva-verde","Uva verde","🍇"],["uva-roxa","Uva roxa","🍇"],["morango","Morango","🍓"],["mirtilo","Mirtilo","🫐"],["melao","Melão","🍈"],["melao-cantalupo","Melão cantalupo","🍈"],["cereja","Cereja","🍒"],["pessego","Pêssego","🍑"],["manga","Manga","🥭"],["abacaxi","Abacaxi","🍍"],["coco","Coco","🥥"],["kiwi","Kiwi","🥝"],["tomate","Tomate","🍅"],["azeitona","Azeitona","🫒"],["abacate","Abacate","🥑"],["pimenta","Pimenta","🌶️"],["mamao","Mamão","🥭"],["maracuja","Maracujá","🍋"],["goiaba","Goiaba","🍐"],["roma","Romã","🍎"],["caqui","Caqui","🍊"]].map(([id,name,emoji])=>({id,name,emoji}));
const state={fruits:[],decisions:loadDecisions(),currentIndex:0,drag:null,toastTimer:null};
const el={stage:document.querySelector("#card-stage"),progressLabel:document.querySelector("#progress-label"),progressValue:document.querySelector("#progress-value"),hint:document.querySelector("#gesture-hint"),matchCount:document.querySelector("#match-count"),toast:document.querySelector("#toast"),historyButton:document.querySelector("#history-button"),dialog:document.querySelector("#history-dialog"),closeHistory:document.querySelector("#close-history"),historyContent:document.querySelector("#history-content"),resetButton:document.querySelector("#reset-button")};
init();
async function init(){bindEvents();try{const response=await fetch("data/fruits.json",{cache:"no-store"});if(!response.ok)throw Error();state.fruits=await response.json()}catch{state.fruits=FALLBACK_FRUITS;showToast("Usando a lista local de segurança.")}render()}
function bindEvents(){document.querySelectorAll("[data-decision]").forEach(button=>button.addEventListener("click",()=>decide(button.dataset.decision)));el.historyButton.addEventListener("click",openHistory);el.closeHistory.addEventListener("click",()=>el.dialog.close());el.resetButton.addEventListener("click",resetExperience);el.dialog.addEventListener("click",event=>{if(event.target===el.dialog)el.dialog.close()});document.addEventListener("keydown",handleKeyboard)}
function loadDecisions(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||{}}catch{return{}}}
function saveDecisions(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.decisions))}
function remaining(){return state.fruits.filter(fruit=>!state.decisions[fruit.id])}
function matches(){return state.fruits.filter(fruit=>state.decisions[fruit.id]==="like")}
function render(){const list=remaining();const reviewed=state.fruits.length-list.length;el.matchCount.textContent=matches().length;el.progressValue.textContent=state.fruits.length?`${reviewed}/${state.fruits.length}`:"";el.progressLabel.textContent=list.length?"frutas para descobrir":"jornada concluída";el.stage.replaceChildren();if(!state.fruits.length){renderError();return}if(!list.length){renderEmpty();el.hint.textContent="suas escolhas estão salvas neste navegador";return}el.hint.textContent="arraste o card ou use os botões";const current=list[state.currentIndex%list.length],next=list[(state.currentIndex+1)%list.length];el.stage.append(createCard(next,false),createCard(current,true))}
function createCard(fruit,current){const card=document.createElement("article");card.className=`fruit-card ${current?"is-current":"is-next"}`;card.dataset.id=fruit.id;card.setAttribute("aria-label",fruit.name);card.innerHTML=`<div class="card-top"><span>descoberta</span><span class="card-number">${String(state.currentIndex+1).padStart(2,"0")}</span></div><div class="fruit-emoji" aria-hidden="true">${fruit.emoji}</div><div class="card-bottom"><h2 class="fruit-name">${fruit.name}</h2><span class="card-tag">fruta</span></div><span class="card-stamp stamp-like">gostei</span><span class="card-stamp stamp-dislike">não gostei</span><span class="card-stamp stamp-unknown">nunca provei</span>`;if(current){card.addEventListener("pointerdown",handlePointerDown);card.addEventListener("pointermove",handlePointerMove);card.addEventListener("pointerup",handlePointerUp);card.addEventListener("pointercancel",handlePointerCancel)}return card}
function handlePointerDown(event){if(event.pointerType==="mouse"&&event.button!==0)return;const card=event.currentTarget;card.setPointerCapture?.(event.pointerId);state.drag={startX:event.clientX,startY:event.clientY,x:0,y:0,card};card.classList.add("dragging")}
function handlePointerMove(event){if(!state.drag)return;state.drag.x=event.clientX-state.drag.startX;state.drag.y=event.clientY-state.drag.startY;const{x,y,card}=state.drag;card.dataset.direction=Math.abs(y)>Math.abs(x)&&y<0?"unknown":x>0?"like":"dislike";card.style.transform=`translate(${x}px,${y}px) rotate(${x*.055}deg)`}
function handlePointerUp(){if(!state.drag)return;const{x,y,card}=state.drag;const horizontal=Math.abs(x),vertical=Math.abs(y),threshold=92,isUp=y<-threshold&&vertical>horizontal,isSide=horizontal>threshold&&horizontal>vertical;if(isUp||isSide)animateDecision(card,isUp?"unknown":x>0?"like":"dislike");else resetCard(card);state.drag=null}
function handlePointerCancel(){if(!state.drag)return;resetCard(state.drag.card);state.drag=null}
function resetCard(card){card.classList.remove("dragging");card.removeAttribute("data-direction");card.style.transform=""}
function animateDecision(card,decision){const x=decision==="like"?innerWidth*1.15:decision==="dislike"?-innerWidth*1.15:0,y=decision==="unknown"?-innerHeight*1.15:0;card.classList.remove("dragging");card.style.transform=`translate(${x}px,${y}px) rotate(${x*.04}deg)`;card.style.opacity="0";setTimeout(()=>decide(decision),180)}
function decide(decision){const list=remaining(),fruit=list[state.currentIndex%Math.max(list.length,1)];if(!fruit)return;state.decisions[fruit.id]=decision;saveDecisions();state.currentIndex=0;showToast({like:`${fruit.name} entrou nos seus matches.`,dislike:`${fruit.name} ficou de fora.`,unknown:`vamos lembrar que você ainda não provou ${fruit.name.toLowerCase()}.`}[decision]);render()}
function handleKeyboard(event){if(el.dialog.open)return;const decisions={ArrowLeft:"dislike",ArrowUp:"unknown",ArrowRight:"like"};if(!decisions[event.key])return;event.preventDefault();decide(decisions[event.key])}
function renderEmpty(){const box=document.createElement("div");box.className="empty-state";box.innerHTML="<h2>você explorou tudo</h2><p>Confira seus matches ou recomece para comparar suas escolhas de novo.</p>";el.stage.append(box)}
function renderError(){const box=document.createElement("div");box.className="error-state";box.innerHTML="<h2>não foi possível carregar</h2><p>A lista de frutas está vazia. Tente novamente.</p><button class=\"retry-button\" type=\"button\">tentar novamente</button>";box.querySelector("button").addEventListener("click",init);el.stage.append(box)}
function openHistory(){renderHistory();el.dialog.showModal()}
function renderHistory(){const list=matches();if(!list.length){el.historyContent.innerHTML="<div class=\"history-empty\">Ainda não há matches. Deslize um card para a direita quando encontrar uma fruta deliciosa.</div>";return}el.historyContent.innerHTML=`<ul class="match-list">${list.map(fruit=>`<li class="match-item"><span class="fruit-emoji" aria-hidden="true">${fruit.emoji}</span><div><p class="match-name">${fruit.name}</p><p class="match-status">gostei</p></div></li>`).join("")}</ul>`}
function resetExperience(){state.decisions={};state.currentIndex=0;saveDecisions();el.dialog.close();render();showToast("sua jornada recomeçou.")}
function showToast(message){clearTimeout(state.toastTimer);el.toast.textContent=message;el.toast.classList.add("is-visible");state.toastTimer=setTimeout(()=>el.toast.classList.remove("is-visible"),2600)}
